// Generated by scripts/generate-content-index.mjs. Do not edit by hand.
import type { CourseLevelId, SectionId } from './courses'

export interface LessonIndexEntry {
  title: string
  description: string
  mission?: string
  canDo?: string
  itemCount: number
}

export const LESSON_INDEX: Record<CourseLevelId, Partial<Record<SectionId, LessonIndexEntry[]>>> = {
  "STARTER": {
    "orientation": [
      {
        "title": "Boarding pass",
        "description": "Understand the app loop before starting JLPT study.",
        "mission": "Learn how Kanji Express turns Japanese into short daily missions.",
        "canDo": "I can explain what I will practice each day and why reviews matter.",
        "itemCount": 3
      }
    ],
    "kana": [
      {
        "title": "Three scripts, one system",
        "description": "Recognize hiragana, katakana, and kanji without panic.",
        "mission": "Look at a platform sign and identify which script you are seeing.",
        "canDo": "I can tell hiragana, katakana, and kanji apart.",
        "itemCount": 5
      },
      {
        "title": "Kana sprint: first sounds",
        "description": "Start reading simple kana by sound, not by memorizing charts perfectly.",
        "mission": "Recognize the first kana used in greetings and survival phrases.",
        "canDo": "I can read a few high-frequency kana chunks.",
        "itemCount": 6
      }
    ],
    "phrases": [
      {
        "title": "Survival phrases",
        "description": "Learn useful expressions before formal grammar.",
        "mission": "Handle your first simple exchange politely.",
        "canDo": "I can use a few phrases immediately, even before I understand every grammar part.",
        "itemCount": 6
      }
    ],
    "sentences": [
      {
        "title": "Sentence signals",
        "description": "See how particles make Japanese sentence order less mysterious.",
        "mission": "Read tiny sentences and spot what each marker does.",
        "canDo": "I can recognize は, を, で, and か as signals in a sentence.",
        "itemCount": 5
      }
    ],
    "study": [
      {
        "title": "How reviews work",
        "description": "Learn why mistakes return and how to study without burning out.",
        "mission": "Set the right expectation for daily review.",
        "canDo": "I can use Again and Got it honestly so SRS helps me remember.",
        "itemCount": 3
      }
    ]
  },
  "N5": {
    "overview": [
      {
        "title": "N5 handover: survival foundations",
        "description": "Understand the scope, target outcomes, and study strategy for your first JLPT level.",
        "mission": "Get oriented before starting N5 lessons.",
        "canDo": "I can explain what N5 covers and what I should be able to do by the end.",
        "itemCount": 4
      },
      {
        "title": "N5 readiness map",
        "description": "See how vocabulary, kanji, grammar, reading, and listening connect before test prep.",
        "mission": "Understand the whole N5 route as one test-readiness system.",
        "canDo": "I can explain what each N5 course section contributes to JLPT readiness.",
        "itemCount": 3
      },
      {
        "title": "Before the N5 mock test",
        "description": "Know the practical abilities you should have before attempting a full practice test.",
        "mission": "Use a readiness checklist instead of guessing whether you are prepared.",
        "canDo": "I can identify the weak skill area that would block my N5 score.",
        "itemCount": 3
      },
      {
        "title": "How to study N5 efficiently",
        "description": "Use short sessions, retrieval, and mixed review to avoid fragile memorization.",
        "mission": "Set the right study loop before finishing N5.",
        "canDo": "I can choose an effective N5 review method for vocabulary, kanji, grammar, reading, and listening.",
        "itemCount": 3
      }
    ],
    "vocab": [
      {
        "title": "Start the journey",
        "description": "Greet someone, give your name, and recognize the first classroom words.",
        "mission": "You have just boarded the Kanji Express and need to introduce yourself.",
        "canDo": "I can exchange basic greetings and say who I am.",
        "itemCount": 8
      },
      {
        "title": "Numbers on the platform",
        "description": "Read basic numbers, prices, and platform information.",
        "mission": "Buy a ticket and find the correct platform.",
        "canDo": "I can understand simple numbers, yen prices, and platform labels.",
        "itemCount": 8
      },
      {
        "title": "Time and schedules",
        "description": "Talk about today, tomorrow, and train departure times.",
        "mission": "Check the departure board before meeting a friend.",
        "canDo": "I can understand simple times and days.",
        "itemCount": 8
      },
      {
        "title": "Food car orders",
        "description": "Order simple food and drinks politely.",
        "mission": "Order from the train food cart.",
        "canDo": "I can ask for food and drinks using ください.",
        "itemCount": 8
      },
      {
        "title": "Places around town",
        "description": "Ask where places are and say where you are going.",
        "mission": "Leave the station and find your destination.",
        "canDo": "I can ask and answer where familiar places are.",
        "itemCount": 8
      },
      {
        "title": "Family and people",
        "description": "Recognize family, friends, and people words used in basic conversations.",
        "mission": "Understand a short conversation about who is at home, school, or work.",
        "canDo": "I can identify common people words in simple N5 sentences.",
        "itemCount": 10
      },
      {
        "title": "Daily routine verbs",
        "description": "Use the basic verbs that appear in N5 schedules and listening prompts.",
        "mission": "Describe one school day from morning to night.",
        "canDo": "I can understand common routine verbs in polite present and past forms.",
        "itemCount": 10
      },
      {
        "title": "Adjectives for everyday choices",
        "description": "Describe places, tickets, weather, and food with common N5 adjectives.",
        "mission": "Choose a route, shop, or meal using simple descriptions.",
        "canDo": "I can recognize common い-adjectives and な-adjectives in N5 questions.",
        "itemCount": 10
      },
      {
        "title": "Question words and counters",
        "description": "Answer who, what, where, when, how much, and how many in beginner contexts.",
        "mission": "Handle ticket counter questions without losing the key detail.",
        "canDo": "I can recognize common N5 question words and simple counters.",
        "itemCount": 10
      },
      {
        "title": "Rules, invitations, and classroom actions",
        "description": "Recognize high-frequency classroom and rule words used with te-form grammar.",
        "mission": "Understand teacher instructions and simple public rules.",
        "canDo": "I can follow short N5 instructions such as please write, please listen, and do not enter.",
        "itemCount": 10
      }
    ],
    "kanji": [
      {
        "title": "Numbers 一 to 五",
        "description": "The first number kanji used in prices, dates, and platforms.",
        "mission": "Recognize number kanji on a ticket machine.",
        "canDo": "I can recognize 一, 二, 三, 四, and 五 in simple words.",
        "itemCount": 5
      },
      {
        "title": "People and language",
        "description": "Kanji for person, Japan, language, student, and teacher.",
        "mission": "Read the words on a classroom name card.",
        "canDo": "I can recognize identity words like 日本人 and 学生.",
        "itemCount": 6
      },
      {
        "title": "Time markers",
        "description": "Kanji for time, now, every, month, and water.",
        "mission": "Read a simple daily schedule.",
        "canDo": "I can recognize basic schedule kanji.",
        "itemCount": 6
      },
      {
        "title": "Numbers 六 to 十 and yen",
        "description": "Complete the most common N5 number kanji used in dates, times, prices, and counters.",
        "mission": "Read prices and times on a ticket machine.",
        "canDo": "I can recognize six through ten and yen in beginner notices.",
        "itemCount": 6
      },
      {
        "title": "Days and dates",
        "description": "Kanji that anchor N5 schedules, dates, and daily routine passages.",
        "mission": "Read a basic calendar and meeting note.",
        "canDo": "I can recognize day, week, year, morning, noon, and evening words.",
        "itemCount": 8
      },
      {
        "title": "Places and movement",
        "description": "Kanji that appear in N5 signs and simple travel passages.",
        "mission": "Read a station-area notice without relying only on kana.",
        "canDo": "I can recognize common place and movement kanji in N5 texts.",
        "itemCount": 8
      },
      {
        "title": "Daily life objects",
        "description": "Kanji for books, food, drink, writing, and common study objects.",
        "mission": "Recognize classroom and daily-life nouns inside simple sentences.",
        "canDo": "I can connect common object kanji to vocabulary used in N5 reading.",
        "itemCount": 8
      },
      {
        "title": "People and family",
        "description": "Kanji for people, family, and basic social roles.",
        "mission": "Read a short self-introduction or family note.",
        "canDo": "I can recognize beginner people and family kanji in context.",
        "itemCount": 8
      },
      {
        "title": "Adjectives and directions",
        "description": "Kanji that support common N5 descriptions and location phrases.",
        "mission": "Understand simple signs and descriptions such as big station, cheap shop, and under the desk.",
        "canDo": "I can recognize common descriptive and position kanji.",
        "itemCount": 8
      },
      {
        "title": "N5 kanji readiness checkpoint",
        "description": "Practice readings and meanings the way N5 language knowledge questions ask them.",
        "mission": "Confirm that the kanji lessons are usable in test-style prompts.",
        "canDo": "I can choose common readings and meanings for beginner kanji compounds.",
        "itemCount": 5
      },
      {
        "title": "Directions and body basics",
        "description": "Kanji that appear in simple signs, directions, and beginner descriptions.",
        "mission": "Read basic direction and body words that often appear in N5 examples.",
        "canDo": "I can recognize direction and body kanji in short N5 phrases.",
        "itemCount": 8
      },
      {
        "title": "Nature and common objects",
        "description": "High-frequency kanji that support weather, food, and simple object descriptions.",
        "mission": "Recognize simple kanji in daily-life words and short notices.",
        "canDo": "I can connect common object and nature kanji to N5 vocabulary.",
        "itemCount": 8
      },
      {
        "title": "Quantities and school life",
        "description": "Kanji for quantities, studying, rest, and everyday school contexts.",
        "mission": "Read basic quantity and school-life words before mixed practice.",
        "canDo": "I can recognize common N5 quantity and study kanji in context.",
        "itemCount": 8
      }
    ],
    "grammar": [
      {
        "title": "Topics, identity, and questions",
        "description": "Build the base sentence frame that JLPT N5 uses everywhere.",
        "mission": "Introduce yourself and ask one identity question without translating word by word.",
        "canDo": "I can use は, も, です, じゃありません, and か in simple identity sentences.",
        "itemCount": 8
      },
      {
        "title": "This, that, and noun linking",
        "description": "Use これ, それ, あれ, この, その, あの, and の correctly.",
        "mission": "Point to things on the platform and ask what they are.",
        "canDo": "I can distinguish standalone demonstratives from noun-modifying demonstratives.",
        "itemCount": 8
      },
      {
        "title": "Core particles in action",
        "description": "Choose the right particle for object, place, direction, time, and company.",
        "mission": "Describe one simple trip with what, where, when, and with whom.",
        "canDo": "I can choose は, が, を, に, へ, で, と, から, and まで in beginner sentences.",
        "itemCount": 10
      },
      {
        "title": "Existence and location",
        "description": "Use あります and います without mixing people, animals, and things.",
        "mission": "Describe what is in a station, classroom, or room.",
        "canDo": "I can say where people and things are, and ask whether something exists.",
        "itemCount": 9
      },
      {
        "title": "Polite verbs and tense",
        "description": "Control present, negative, past, and past-negative ます forms.",
        "mission": "Talk about today, yesterday, and tomorrow with accurate verb endings.",
        "canDo": "I can recognize and form basic polite verb tenses tested at N5.",
        "itemCount": 9
      },
      {
        "title": "Adjectives and noun modifiers",
        "description": "Handle い-adjectives, な-adjectives, and adjective negatives.",
        "mission": "Describe food, tickets, stations, and people naturally.",
        "canDo": "I can choose the right adjective ending before nouns and before です.",
        "itemCount": 9
      },
      {
        "title": "Te-form for useful actions",
        "description": "Use て-form for requests, permission, prohibition, and ongoing actions.",
        "mission": "Ask someone to repeat, check permission, and understand simple rules.",
        "canDo": "I can understand common N5 て-form patterns in signs and short conversations.",
        "itemCount": 9
      },
      {
        "title": "Wanting, inviting, and offering",
        "description": "Use たい, ましょう, ませんか, and ましょうか for simple social actions.",
        "mission": "Invite a friend, say what you want to do, and offer help.",
        "canDo": "I can understand beginner invitation and desire patterns.",
        "itemCount": 9
      },
      {
        "title": "Reasons, sequence, and contrast",
        "description": "Connect short sentences with から, そして, でも, and けど.",
        "mission": "Explain a simple reason and follow a two-sentence message.",
        "canDo": "I can understand basic connectors in N5 reading and listening.",
        "itemCount": 9
      },
      {
        "title": "Comparisons and preferences",
        "description": "Answer common N5 comparison questions using より, ほうが, 一番, and 好き.",
        "mission": "Say which route, food, or subject you prefer.",
        "canDo": "I can understand basic comparison and preference questions.",
        "itemCount": 9
      }
    ],
    "listening": [
      {
        "title": "Greeting on board",
        "description": "Slow short exchanges about names and roles.",
        "mission": "Understand a first meeting on the train.",
        "canDo": "I can pick out names, roles, and greetings from a slow dialogue.",
        "itemCount": 3
      },
      {
        "title": "Station audio",
        "description": "Short announcements about platforms, time, and tickets.",
        "itemCount": 3
      },
      {
        "title": "Classroom instructions",
        "description": "Understand short teacher directions using てください and てはいけません.",
        "mission": "Follow basic classroom audio before a test starts.",
        "canDo": "I can understand simple requests and rules in slow N5 audio.",
        "itemCount": 3
      },
      {
        "title": "Daily routine audio",
        "description": "Catch time, frequency, and verb tense in slow everyday statements.",
        "mission": "Understand a short morning routine.",
        "canDo": "I can identify when an action happens and whether it is past or habitual.",
        "itemCount": 3
      },
      {
        "title": "Shopping and price audio",
        "description": "Understand short exchanges about food, quantity, and money.",
        "mission": "Buy food from a counter using slow Japanese.",
        "canDo": "I can catch item, quantity, and price in a simple transaction.",
        "itemCount": 3
      },
      {
        "title": "Immediate response practice",
        "description": "Choose the natural reply to short N5-level prompts.",
        "mission": "React to simple questions without translating every word.",
        "canDo": "I can choose an appropriate beginner response to a short spoken prompt.",
        "itemCount": 3
      }
    ],
    "reading": [
      {
        "title": "Name cards and signs",
        "description": "Read very short identity texts and station signs.",
        "mission": "Read the first signs on the Kanji Express platform.",
        "canDo": "I can understand names, roles, and platform signs.",
        "itemCount": 3
      },
      {
        "title": "Simple schedules",
        "description": "Read time, day, and place from short messages.",
        "itemCount": 2
      },
      {
        "title": "Classroom note",
        "description": "Read a short instruction note with names, time, and actions.",
        "mission": "Understand what to do before class starts.",
        "canDo": "I can extract action, time, and rule from a short school note.",
        "itemCount": 3
      },
      {
        "title": "Store notice",
        "description": "Read a simple shop notice with price, item, and location information.",
        "mission": "Find what to buy and how much it costs.",
        "canDo": "I can understand simple price and item information in a notice.",
        "itemCount": 3
      },
      {
        "title": "Daily schedule",
        "description": "Read a beginner schedule and distinguish yesterday, today, and tomorrow.",
        "mission": "Understand a learner’s day from a short message.",
        "canDo": "I can identify time, action, and sequence in a short N5 passage.",
        "itemCount": 3
      },
      {
        "title": "Invitation message",
        "description": "Read a short invitation and understand time, place, and response.",
        "mission": "Decide whether you can meet a friend.",
        "canDo": "I can understand an N5-level invitation message.",
        "itemCount": 3
      }
    ],
    "tests": [
      {
        "title": "Checkpoint 1: sentence roles",
        "description": "JLPT-style review of topics, demonstratives, particles, and existence.",
        "mission": "Pass the first N5 grammar gate before moving into verb tense.",
        "canDo": "I can choose basic particles and sentence frames in short N5 questions.",
        "itemCount": 6
      },
      {
        "title": "Checkpoint 2: forms and functions",
        "description": "JLPT-style review of verbs, adjectives, te-form, connectors, and comparisons.",
        "mission": "Prove you can pick forms by meaning, not by memorized English labels.",
        "canDo": "I can answer N5 grammar questions involving tense, requests, desire, reasons, and comparisons.",
        "itemCount": 7
      },
      {
        "title": "Checkpoint 3: vocabulary and kanji",
        "description": "JLPT-style review of N5 word meaning, readings, and kanji recognition.",
        "mission": "Check whether the N5 words and kanji are recognizable in test format.",
        "canDo": "I can answer common N5 vocabulary and kanji questions without seeing translations first.",
        "itemCount": 6
      },
      {
        "title": "Checkpoint 4: reading and listening",
        "description": "Mixed N5 practice using short passages, notices, and spoken prompts.",
        "mission": "Prove you can extract concrete information across input types.",
        "canDo": "I can answer who, where, when, what, and why questions from short N5 input.",
        "itemCount": 6
      },
      {
        "title": "Mock section: language knowledge",
        "description": "A denser N5-style set for vocabulary, readings, particles, and verb/adjective forms.",
        "mission": "Handle a mixed language-knowledge block without relying on lesson order.",
        "canDo": "I can answer mixed vocabulary, kanji, and grammar questions in one sitting.",
        "itemCount": 10
      },
      {
        "title": "Mock section: sentence assembly",
        "description": "Practice JLPT-style sentence order and connector logic with short N5 sentences.",
        "mission": "Build correct sentence order instead of only choosing isolated particles.",
        "canDo": "I can identify the best N5 sentence order and connector.",
        "itemCount": 6
      },
      {
        "title": "Mock section: reading",
        "description": "A longer reading block that mixes notices, schedules, invitations, and simple descriptions.",
        "mission": "Read several short N5 passages in sequence and retain key facts.",
        "canDo": "I can answer concrete information questions from multiple N5 text types.",
        "itemCount": 6
      },
      {
        "title": "Mock section: listening",
        "description": "A compact listening block with task, point, and response-style N5 questions.",
        "mission": "Answer several audio-style prompts without seeing a grammar label first.",
        "canDo": "I can extract action, time, place, price, permission, and response from slow N5 prompts.",
        "itemCount": 6
      },
      {
        "title": "Readiness diagnosis",
        "description": "Use the final N5 checklist to decide what to review before a real mock test.",
        "mission": "Turn checkpoint results into a focused review plan.",
        "canDo": "I can identify which N5 skill to review next based on missed question types.",
        "itemCount": 4
      }
    ]
  },
  "N4": {
    "overview": [
      {
        "title": "N4 handover: everyday autonomy",
        "description": "See how N4 expands N5 into routine daily-life communication.",
        "mission": "Prepare for the shift from single facts to connected daily actions.",
        "canDo": "I can describe what N4 adds and how it changes my study load.",
        "itemCount": 4
      }
    ],
    "vocab": [
      {
        "title": "Plans and errands",
        "description": "Words for daily plans, shopping, and obligations.",
        "itemCount": 6
      }
    ],
    "kanji": [
      {
        "title": "Daily movement",
        "description": "Kanji for plans, errands, and transportation.",
        "itemCount": 6
      }
    ],
    "grammar": [
      {
        "title": "Plans and reasons",
        "description": "Use dictionary form, つもり, and ので for everyday planning.",
        "itemCount": 4
      }
    ],
    "listening": [
      {
        "title": "Changing plans",
        "description": "Understand slow daily conversations about plans.",
        "itemCount": 2
      }
    ],
    "reading": [
      {
        "title": "Short messages",
        "description": "Read practical messages about errands and plans.",
        "itemCount": 2
      }
    ],
    "tests": [
      {
        "title": "N4 planning drill",
        "description": "Mixed review of plans, reasons, and practical reading.",
        "itemCount": 3
      }
    ]
  },
  "N3": {
    "overview": [
      {
        "title": "N3 handover: the bridge",
        "description": "Understand the jump from beginner control to intermediate comprehension.",
        "mission": "Prepare for nuance, longer input, and less translated thinking.",
        "canDo": "I can explain why N3 feels different from N4 and how to study it.",
        "itemCount": 4
      }
    ],
    "vocab": [
      {
        "title": "Work and experience",
        "description": "Intermediate words for everyday work and social topics.",
        "itemCount": 6
      }
    ],
    "kanji": [
      {
        "title": "Intermediate work kanji",
        "description": "Kanji common in notices and workplace messages.",
        "itemCount": 6
      }
    ],
    "grammar": [
      {
        "title": "Nuance and explanation",
        "description": "Patterns that explain expectations, reasons, and contrast.",
        "itemCount": 4
      }
    ],
    "listening": [
      {
        "title": "Near-natural notices",
        "description": "Understand key points in practical announcements.",
        "itemCount": 2
      }
    ],
    "reading": [
      {
        "title": "Practical explanations",
        "description": "Read short explanations and identify the reason or main point.",
        "itemCount": 2
      }
    ],
    "tests": [
      {
        "title": "N3 bridge drill",
        "description": "Mixed review of intermediate vocabulary and grammar.",
        "itemCount": 3
      }
    ]
  },
  "N2": {
    "overview": [
      {
        "title": "N2 handover: independent fluency",
        "description": "Understand the shift into broad topics, formal prose, and faster listening.",
        "mission": "Prepare for reading and listening that assumes you can follow argument structure.",
        "canDo": "I can explain the N2 scope and the study habits required for independent comprehension.",
        "itemCount": 4
      }
    ],
    "vocab": [
      {
        "title": "Society and work",
        "description": "Formal words common in news, reports, and workplace Japanese.",
        "itemCount": 6
      }
    ],
    "kanji": [
      {
        "title": "Formal report kanji",
        "description": "Kanji often seen in reports and news articles.",
        "itemCount": 6
      }
    ],
    "grammar": [
      {
        "title": "Formal reasoning",
        "description": "Patterns for reports, essays, and workplace explanations.",
        "itemCount": 4
      }
    ],
    "listening": [
      {
        "title": "Workplace briefings",
        "description": "Understand the key decision in formal spoken explanations.",
        "itemCount": 1
      }
    ],
    "reading": [
      {
        "title": "Opinion paragraphs",
        "description": "Read a short formal argument and identify the claim.",
        "itemCount": 1
      }
    ],
    "tests": [
      {
        "title": "N2 formal drill",
        "description": "Mixed review of formal vocabulary and grammar.",
        "itemCount": 2
      }
    ]
  },
  "N1": {
    "overview": [
      {
        "title": "N1 handover: advanced mastery",
        "description": "Understand the scope of dense, abstract, nuanced Japanese.",
        "mission": "Prepare for high-density input, register control, and implicit meaning.",
        "canDo": "I can explain what N1 requires beyond memorizing advanced word lists.",
        "itemCount": 4
      }
    ],
    "vocab": [
      {
        "title": "Advanced abstractions",
        "description": "Nuanced words for editorials, critiques, and academic prose.",
        "itemCount": 6
      }
    ],
    "kanji": [
      {
        "title": "Advanced abstract kanji",
        "description": "Kanji found in dense written Japanese.",
        "itemCount": 6
      }
    ],
    "grammar": [
      {
        "title": "Advanced written patterns",
        "description": "Emphatic and formal expressions for dense prose.",
        "itemCount": 4
      }
    ],
    "listening": [
      {
        "title": "Dense spoken argument",
        "description": "Track stance and implication in natural-speed explanations.",
        "itemCount": 1
      }
    ],
    "reading": [
      {
        "title": "Editorial stance",
        "description": "Identify nuanced claims in abstract prose.",
        "itemCount": 1
      }
    ],
    "tests": [
      {
        "title": "N1 advanced drill",
        "description": "Mixed review of nuanced vocabulary and advanced grammar.",
        "itemCount": 2
      }
    ]
  }
}
